export { default as Home } from './Home'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Destinations } from './Destinations'
export { default as Yachts } from './Yachts'
export { default as CharterInquiry } from './CharterInquiry' 
